# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Intelect' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking'
  pod 'JSONModel'
  # Pods for Intelect

  target 'IntelectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntelectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
